# The name of the workflow, which will appear on the GitHub Actions tab.
name: Deploy Webpage

# When the workflow should run (Triggers on push to the 'main' branch)
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A futtatandó feladatok (job-ok)
jobs:
  # A build és deploy feladat neve.
  build-and-deploy:
    # A környezet, amiben futni fog (leggyakrabban Ubuntu a CI/CD-hez)
    environment:
      name: production
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ezt kell a gh-pages-nek a push-hoz
      pages: write    # Ezt kell a GitHub Pages deploy-hoz
      id-token: write
    # A feladat lépései
    steps:
      # 2. Kód lekérése a repository-ból (Checkout)
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # 3. Node.js környezet beállítása
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 4. Függőségek telepítése
      - name: Install dependencies
        run: npm ci
        working-directory: ./newice

      # 5. Git felhasználói adatok konfigurálása
      - name: Configure Git user identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: ./newice

      # 6. A build és deploy parancs futtatása
      - name: Run Deploy Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npx gh-pages -d build -b gh-pages --repo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        working-directory: ./newice